import "../globals.css";

import ClientRootLayout from "./client-layout";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }) => {
  return (
      <ClientRootLayout>{children}</ClientRootLayout>
  );
};

export default RootLayout;
